[Service]
ExecStart=
ExecStart=/usr/bin/prometheus-node-exporter $ARGS --collector.systemd --collector.systemd.unit-include=(pvedaemon|pveproxy|pvestatd|pvescheduler|pve-cluster|alloy|homelab-alert-test)[.]service
